#!/bin/bash

# AI: Code generated by Google Gemini

# Hard-coded configuration
REQUEST_URL="/directory/youpi.bla"
HOST="localhost:8080"

#PIPE_OUTPUT_TO="cat -e"
PIPE_OUTPUT_TO="nc localhost 8080"

GREEN='\033[1;32m'
LIGHT_BLUE='\033[1;34m'
LIGHT_YELLOW='\033[1;33m'
COLOR_RESET='\033[0m'

# Function to display usage instructions
print_usage() {
	echo "Usage:"
	echo "  $0 normal <total_bytes>"
	echo "  $0 chunked <total_bytes> <chunk_size>"
	exit 1
}

# 1. Validate the minimum number of arguments
if [ -z "$1" ] || [ -z "$2" ]; then
	print_usage
fi

MODE="$1"
TOTAL_BYTES="$2"

# Validate that total_bytes is a valid integer
if ! [[ "$TOTAL_BYTES" =~ ^[0-9]+$ ]]; then
	echo "Error: total_bytes must be a positive integer."
	print_usage
fi

# 2. Process based on the selected mode
if [ "$MODE" = "normal" ]; then
	# Construct a simple body filled with 'A's matching the total bytes
	BODY=$(printf 'A%.0s' $(seq 1 "$TOTAL_BYTES"))

	# Group headers and body, then pass to cat -e
	THE_HTTP_REQUEST=$({
		printf "POST %s HTTP/1.1\r\n" "$REQUEST_URL"
		printf "Host: %s\r\n" "$HOST"
		#		printf "Content-Type: text/plain\r\n"
		printf "Content-Length: %d\r\n" "$TOTAL_BYTES"
		printf "Connection: close\r\n"
		printf "\r\n"
		printf "%s" "$BODY"
	})

elif [ "$MODE" = "chunked" ]; then
	# Validate the third argument for chunked mode
	if [ -z "$3" ]; then
		echo "Error: chunked mode requires a chunk_size argument."
		print_usage
	fi

	CHUNK_SIZE="$3"

	# Validate that chunk_size is a valid integer
	if ! [[ "$CHUNK_SIZE" =~ ^[0-9]+$ ]] || [ "$CHUNK_SIZE" -le 0 ]; then
		echo "Error: chunk_size must be an integer greater than 0."
		print_usage
	fi

	# Group the multi-line output generation block
	THE_HTTP_REQUEST=$({
		# Print main headers
		printf "POST %s HTTP/1.1\r\n" "$REQUEST_URL"
		printf "Host: %s\r\n" "$HOST"
		#		printf "Content-Type: text/plain\r\n"
		printf "Transfer-Encoding: chunked\r\n"
		printf "Connection: close\r\n"
		printf "\r\n"

		# Generate chunked body payloads
		REMAINING=$TOTAL_BYTES
		while [ "$REMAINING" -gt 0 ]; do
			# Determine size of current chunk
			if [ "$REMAINING" -lt "$CHUNK_SIZE" ]; then
				CURRENT_CHUNK=$REMAINING
			else
				CURRENT_CHUNK=$CHUNK_SIZE
			fi

			# Print chunk size in Hexadecimal followed by CRLF
			printf "%x\r\n" "$CURRENT_CHUNK"

			# Print the chunk data ('B's) followed by CRLF
			printf 'B%.0s' $(seq 1 "$CURRENT_CHUNK")
			printf "\r\n"

			# Decrement remaining bytes
			REMAINING=$((REMAINING - CURRENT_CHUNK))
		done

		# Print final mandatory terminating chunk (0) and empty trailer line
		printf "0\r\n"
		printf "\r\n"
	})

else
	echo "Error: Invalid mode '$MODE'. Use 'normal' or 'chunked'."
	print_usage
fi

if [ ! -z "$THE_HTTP_REQUEST" ]; then
	printf "\n"
	printf "$GREEN"
	printf "SENDING THE HTTP REQUEST TO $HOST"
	printf "$COLOR_RESET"
	printf "\n"
	printf "$THE_HTTP_REQUEST"
	printf "$GREEN"
	printf "==FIN=="
	printf "\n"
	printf "$COLOR_RESET"

	THE_RESPONSE=$(printf "$THE_HTTP_REQUEST" | $PIPE_OUTPUT_TO)
	printf "\n"
	printf "$LIGHT_YELLOW"
	printf "GOT RESPONSE:"
	printf "$COLOR_RESET"
	printf "\n"
	printf "$THE_RESPONSE"
	printf "$LIGHT_YELLOW"
	printf "==FIN=="
	printf "$COLOR_RESET"
	printf "\n\n"
fi
